language: node_js

cache:
  directories:
    - node_modules
    - dist
    - gh-pages

# install dependencies
install:
  - npm ci --silent

# the jobs for building and deploying
jobs:
  include:
    - stage: test
      script:
        - npm run test:ci

    - stage: build
      script:
        # build polyfill
        - npm run build
        # create the target
        - mkdir -p ./gh-pages/dist
        # copy the built folder and html to target
        - cp -R dist/* ./gh-pages/dist
        - cp index.html README.md ./gh-pages

    - stage: github pages
      if: branch = master
      script: echo "deploying github pages"
      deploy:
        provider: pages
        skip-cleanup: true
        keep-history: true
        local-dir: gh-pages
        github-token: $GITHUB_TOKEN
        on:
          branch: master

    - stage: npm release
      if: tag IS present
      script: echo "releasing to npm"
      deploy:
        provider: npm
        skip-cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true
