/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CarageButton {}
  interface CarageRoot {}
}

declare global {


  interface HTMLCarageButtonElement extends Components.CarageButton, HTMLStencilElement {}
  var HTMLCarageButtonElement: {
    prototype: HTMLCarageButtonElement;
    new (): HTMLCarageButtonElement;
  };

  interface HTMLCarageRootElement extends Components.CarageRoot, HTMLStencilElement {}
  var HTMLCarageRootElement: {
    prototype: HTMLCarageRootElement;
    new (): HTMLCarageRootElement;
  };
  interface HTMLElementTagNameMap {
    'carage-button': HTMLCarageButtonElement;
    'carage-root': HTMLCarageRootElement;
  }
}

declare namespace LocalJSX {
  interface CarageButton {}
  interface CarageRoot {}

  interface IntrinsicElements {
    'carage-button': CarageButton;
    'carage-root': CarageRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'carage-button': LocalJSX.CarageButton & JSXBase.HTMLAttributes<HTMLCarageButtonElement>;
      'carage-root': LocalJSX.CarageRoot & JSXBase.HTMLAttributes<HTMLCarageRootElement>;
    }
  }
}


